# Reference: https://github.com/i3/i3/blob/next/etc/config

start-at-login = true

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[workspace-to-monitor-force-assignment]
    1 = 'main'                       # Main monitor
    2 = 'main'                       # Main monitor
    3 = 'main'                       # Main monitor
    4 = 'main'                       # Main monitor
    5 = 'main'                       # Main monitor
    6 = 'main'                       # Main monitor
    7 = 'main'                       # Main monitor
    A = 'secondary'                  # Non-main monitor in case when there are only two monitors
    S = 'secondary'                  # Non-main monitor in case when there are only two monitors
    D = 'secondary'                  # Non-main monitor in case when there are only two monitors

[mode.main.binding]
    # See: https://nikitabobko.github.io/AeroSpace/goodies#open-a-new-window-with-applescript
    alt-enter = '''exec-and-forget osascript -e '
    tell application "Terminal"
        do script
        activate
    end tell'
    '''

    # normalizations

    # alt-f = 'fullscreen'

    alt-v = 'layout v_accordion' # 'layout stacking' in i3
    alt-t = 'layout h_accordion' # 'layout tabbed' in i3
    alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

    alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

    # Not supported, because this command is redundant in AeroSpace mental model.
    # See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
    #alt-space = 'focus toggle_tiling_floating'

    # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
    # should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
    # alt-a = 'focus parent'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'
    alt-0 = 'workspace 10'
    alt-a = 'workspace A'
    alt-s = 'workspace S'
    alt-d = 'workspace D'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'
    alt-shift-0 = 'move-node-to-workspace 10'
    alt-shift-a = 'move-node-to-workspace A'
    alt-shift-s = 'move-node-to-workspace S'
    alt-shift-d = 'move-node-to-workspace D'

    alt-shift-c = 'reload-config'

