[aw-qt]
#autostart_modules = ["aw-server", "aw-watcher-afk", "aw-watcher-window"]
autostart_modules = ["aw-server", "aw-watcher-window-wayland"]

[aw-qt-testing]
autostart_modules = ["aw-server", "aw-watcher-window-wayland"]
