return {}
-- return
-- {
--   "catppuccin/nvim",
--   lazy = false,
--   name = "catppuccin",
--   priority = 1000,
--   config = function()
--     require("catppuccin").setup({
--       flavour = "mocha", -- latte, frappe, macchiato, mocha
--       no_italic = true,
--       transparent_background = true,
--       term_colors = true,
--       navic = {
--         enabled = false,
--         custom_bg = "NONE",
--       },
--       floating_border = "on",
--       native_lsp = {
--         enabled = true,
--       },
--       color_overrides = {},
--       custom_highlights = function(colors)
--         return {
--           NeoTreeCursorLine = { bg = colors.surface2 },
--         }
--       end,
--       integrations = {
--         cmp = {
--           enabled = true,
--           border = {
--             completion = true,
--             documentation = true
--           }
--         },
--         gitsigns = true,
--         telescope = true,
--         notify = true,
--         mini = true,
--         fidget = true,
--         leap = true,
--         neotree = true,
--         noice = true,
--         navic = true,
--         treesitter = true,
--         treesitter_context = true,
--         symbols_outline = true,
--         lsp_trouble = true,
--         which_key = true,
--         native_lsp = {
--           enabled = true,
--           virtual_text = {
--             errors = { "italic" },
--             hints = { "italic" },
--             warnings = { "italic" },
--             information = { "italic" },
--           },
--           underlines = {
--             errors = { "underline" },
--             hints = { "underline" },
--             warnings = { "underline" },
--             information = { "underline" },
--           },
--         },
--       },
--     })
--     -- vim.cmd([[colorscheme catppuccin]])
--   end,
-- }
